module: SwiftNumber
author: Károly Lőrentey, Legend Labs, Inc
theme: fullwidth
output: ./docs
author_url: "https://x.com/joinlegend"
github_url: "https://github.com/legend-hq/SwiftNumber"
root_url: "https://legend-hq.github.io/SwiftNumber/reference/" 
xcodebuild_arguments: ["-workspace", "SwiftNumber.xcworkspace", "-scheme", "SwiftNumber-macOS"]